# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://srsogroup.com
title: SR Solutions Group, LLC
email: ryan@srsogroup.com

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  #- title: twitter
  #  url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/SRSolutionsGroup
  #- title: linkedin
  #  url:
